### ISSUE TITLE
Bug in Node.js <= 14. No sourceMap for CSS.

### ISSUE THREAD

**Issue by Sir-Will** [webdiscus/pug-plugin#2]
Hey,

I'm using `extractCss` which is working so far, but I couldn't figure out how to enable the source map creation with this.
I have added `sourceMap: true` to css- postcss- and sass-loader, but it's not creating one.

How do I enable source map with pug plugin?

**Comment by webdiscus** [comment]
Hallo @Sir-Will,

the `pug-plugin` extract css and sourceMap from result  of the `css-loader`.

The example of `webpack.config.js` from [the test case](https://github.com/webdiscus/pug-plugin/tree/master/test/cases/entry-sass-pug-devel):

```js
const path = require('path');
const PugPlugin = require('../../../');

// if is FALSE then will be generated the sourceMap
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
  mode: isProduction ? 'production' : 'development', // <-- only in mode  'development' is generated sourceMap
  devtool: isProduction ? false : 'source-map',  // <-- if devtool is not false then is generated sourceMap

  output: {
    path: path.join(__dirname, 'public/'),
    publicPath: '/',
  },

  entry: {
    styles: './src/assets/main.scss',
    index: './src/index.pug',
  },

  plugins: [
    new PugPlugin({
      modules: [
        PugPlugin.extractCss({
          filename: isProduction ? '[name].[contenthash:8].css' : '[name].css',
        }),
      ],
    }),
  ],

  module: {
    rules: [
      {
        test: /\.(pug)$/,
        loader: PugPlugin.loader,
      },
      {
        test: /\.(css|sass|scss)$/,
        use: ['css-loader', 'sass-loader'],
      },
    ],
  },
};
```

If the `isProduction` is `false` then the sourceMap is  generated as embedded data in self css-file, like following:

```css
h1 {
  color: darkred;
}
/*# sourceURL=webpack://./src/assets/main.scss */
/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8uL3NyYy9hc3NldHMvbWFpbi5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUNBO0VBQ0UsY0FGTTtBQUVSIiwic291cmNlc0NvbnRlbnQiOlsiJGNvbG9yOiBkYXJrcmVkO1xuaDEge1xuICBjb2xvcjogJGNvbG9yO1xufSJdLCJzb3VyY2VSb290IjoiIn0= */
```

It's legal, supported by all browsers. Additional `*.css.map` files are no longer generated. It's very practical. Instead of two files, only one is loaded in the browser. The mapping to source of scss works fine in all browser. The mapping is only relevant for development. In Production will be generate pure css w/o sourceMap.
