### ISSUE TITLE
Can't resolve the file for data-url in CSS

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/pug-plugin#6]
When using inline data in CSS via a data-url, the pug plugin tries to resolve the url which throws an error:
```
[pug-plugin] Can't resolve the file data:image/png;base64,iVBORw0K...
```

```css
.image {
  background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSU...==);
}
```

>  this issue is extracted from the [ticket](https://github.com/webdiscus/pug-plugin/issues/3) to split one issue to two differents.
